import re
import glob
import pandas as pd
from snakemake.utils import min_version

min_version("7.32.3")

configfile: "../config/hpcnode.yaml"

SAMPLES = pd.read_table(config["sample_sheet"], sep="\t")["sample"].tolist()
LEAF_SAMPLES = [x for x in SAMPLES if "Leaf" in x]

LOG_DIR = f"{config['log_prefix']}"
STAR_DIR = f"{config['results_prefix']}/star"
DEG_DIR = f"{config['results_prefix']}/deg_analysis"
FIGURES_DIR = f"{config['results_prefix']}/figures"

include: "rules/deg_analysis.smk"

rule all:
    input:
        expand(rules.deg_analysis.output, sample=SAMPLES)
